apiVersion: 1.0
metadata:
  codeName: "com.hedon_haven.tester_external_dart"
  prettyName: "Tester as External (dart)"
  version: v0.2.0
  developer: "Hedon dev"
  contactEmail: "contact@hedon-haven.top"
  description: "A tester plugin written in dart for testing external plugins"
  updateUrl: "https://github.com/Hedon-Haven/3rd-party-plugin-examples/releases/latest/download/tester_external_dart-update.yaml"
  issuesUrl: "https://github.com/Hedon-Haven/3rd-party-plugin-examples/issues"

providerData:
  iconUrl: "https://placehold.co/favicon.ico"
  serviceUrl: "https://example.com"
  handleUrls:
    - "https://example.com"
    - "https://example.org"

initialPageCounts:
  initialHomePage: 0
  initialSearchResultsPage: 0
  initialCommentsPage: 0
  initialVideoSuggestionsPage: 0
  initialAuthorVideosPage: 0