apiVersion: 1.0
metadata:
  codeName: "com.hedon_haven.tester_external_js"
  prettyName: "Tester as External (js)"
  version: v0.3.0
  developer: "Hedon dev"
  contactEmail: "contact@hedon-haven.top"
  description: "A tester plugin written in JavaScript for testing external plugins"
  updateUrl: "https://github.com/Hedon-Haven/3rd-party-plugin-examples/releases/latest/download/tester_external_js-update.yaml"
  issuesUrl: "https://github.com/Hedon-Haven/3rd-party-plugin-examples/issues"

providerData:
  iconUrl: "https://placehold.co/favicon.ico"
  serviceUrl: "https://example.com"
  handleUrls:
    - "https://example.com/home"
    - "https://example.com/search"
    - "https://example.com/video"
    - "https://example.com/author"

initialPageCounts:
  initialHomePage: 0
  initialSearchResultsPage: 0
  initialCommentsPage: 0
  initialVideoSuggestionsPage: 0
  initialAuthorVideosPage: 0