apiVersion: 1.0
metadata:
  codeName: "com.hedon_haven.tester_external_js"
  prettyName: "Tester as External (js)"
  version: v0.2.0
  developer: "Hedon dev"
  contactEmail: "contact@hedon-haven.top"
  description: "A tester plugin written in JavaScript for testing external plugins"
  updateUrl: "https://github.com/Hedon-Haven/3rd-party-plugin-examples/releases/download/tester_external_js-update.yaml"
  issuesUrl: "https://github.com/Hedon-Haven/3rd-party-plugin-examples/issues"

providerData:
  iconUrl: "https://placehold.co/favicon.ico"
  providerUrl: "https://tester-external-plugin.com"

initialPageCounts:
  initialHomePage: 0
  initialSearchResultsPage: 0
  initialCommentsPage: 0
  initialVideoSuggestionsPage: 0
  initialAuthorVideosPage: 0